// Generated by CoffeeScript 1.6.3
/*
This example is a copy of "basic.html", but with event bindings after.
Open your browser's console to see the "click", "overNode" and
"outNode" events logged.
*/


(function() {
  var generateGraph, l, lb, s;

  l = 12;

  lb = 16;

  generateGraph = function(n, e) {
    var E, N, g, num, _i, _j, _ref, _ref1;
    g = {
      nodes: [],
      edges: []
    };
    N = n;
    E = e;
    for (num = _i = 0, _ref = N - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; num = 0 <= _ref ? ++_i : --_i) {
      g.nodes.push({
        id: "n" + num,
        label: "Node " + num,
        x: Math.random(),
        y: Math.random(),
        size: l,
        color: "#666"
      });
    }
    for (num = _j = 0, _ref1 = E - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; num = 0 <= _ref1 ? ++_j : --_j) {
      g.edges.push({
        id: "e" + num,
        source: "n" + (Math.random() * N | 0),
        target: "n" + (Math.random() * N | 0),
        size: Math.random(),
        color: "#ccc"
      });
    }
    return g;
  };

  s = new sigma({
    graph: generateGraph(25, 100),
    container: "graph-container",
    defaultEdgeType: "curve"
  });

  s.bind("overNode", function(e) {
    e.data.node.size = lb;
    return console.log(e.type, e.data.node.label);
  });

  s.bind("outNode", function(e) {
    e.data.node.size = l;
    return console.log(e.type, e.data.node.label);
  });

  s.startForceAtlas2();

}).call(this);

/*
//@ sourceMappingURL=graph.map
*/
